version: '3'
services:
  schedule-api:
    image: schedule-api:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    ports:
      - 3000:3000
    network_mode: "host"